/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package filters;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author pawel
 */
public class FrequencyFilteringPanel extends javax.swing.JPanel {
    
    float[] param;
    FrequencyFiltering filter;
    JRadioButton[] rbTab;
    JTextField[] paramTab;

    /**
     * Creates new form FrequencyFilteringPanel
     */
    public FrequencyFilteringPanel() {
        initComponents();
        ButtonGroup rbg = new ButtonGroup();
        rbTab = new JRadioButton[] {
            jRadioButton1, jRadioButton2, jRadioButton3,
            jRadioButton4, jRadioButton5, jRadioButton6
        };
        paramTab = new JTextField[] {
            jTextField1  , jTextField2, jTextField3, jTextField4
        };
        
        for (int i = 0; i < paramTab.length; i++) {
            paramTab[i].setVisible(false);
            
        }
        
        param1.setVisible(false);
        param2.setVisible(false);
        param3.setVisible(false);
        param4.setVisible(false);
        
        for(int i=0; i<rbTab.length; ++i) {
            rbg.add(rbTab[i]);
            rbTab[i].addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                         if ( e.getSource().equals(jRadioButton1) || e.getSource().equals(jRadioButton2)) {
                             jTextField1.setVisible(true); param1.setVisible(true);
                             jTextField2.setVisible(true); param2.setVisible(true);
                             jTextField3.setVisible(false); param3.setVisible(false);
                             jTextField4.setVisible(false); param4.setVisible(false);
                             
                            param1.setText("%(0,1)");
                            param2.setText("k(1,n)");
                            
                    } else if (e.getSource().equals(jRadioButton3) || e.getSource().equals(jRadioButton4)) {
                        jTextField1.setVisible(true); param1.setVisible(true);
                        jTextField2.setVisible(true); param2.setVisible(true);
                        jTextField3.setVisible(true); param3.setVisible(true);
                        
                        param1.setText("Low %(0,1)");
                        param2.setText("Hi %(0,1)");
                        param3.setText("k(1,n)");
                    } else if ( e.getSource().equals(jRadioButton5)) {
                        jTextField1.setVisible(true); param1.setVisible(true);
                        jTextField2.setVisible(true); param2.setVisible(true);
                        jTextField3.setVisible(true); param3.setVisible(true);
                        jTextField4.setVisible(true); param4.setVisible(true);
                        
                        param1.setText("Low %(0,1)");
                        param2.setText("Hi %(0,1)");
                        param3.setText("ang(1,180)");
                        param4.setText("point(ex 1,0)");
                        
                    } else if ( e.getSource().equals(jRadioButton6)) {
                        jTextField1.setVisible(true); param1.setVisible(true);
                        jTextField2.setVisible(true); param2.setVisible(true);
                        jTextField3.setVisible(false); param3.setVisible(false);
                        jTextField4.setVisible(false); param4.setVisible(false);
                        param1.setText("l:");
                        param2.setText("k:");
                        
                    }
                }
            });
               
        }
    }
    public FrequencyFilteringPanel(FrequencyFiltering f) {
        this();
        this.filter = f;
        param= new float[4];
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        param1 = new javax.swing.JLabel();
        param2 = new javax.swing.JLabel();
        param3 = new javax.swing.JLabel();
        param4 = new javax.swing.JLabel();

        jRadioButton1.setText("low-pass");

        jRadioButton2.setText("high-pass");

        jRadioButton3.setText("band-pass");

        jRadioButton4.setText("band-stop");

        jRadioButton5.setText("edge detect");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Apply");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCheckBox1.setText("fazy");

        jCheckBox2.setText("magniute");

        jLabel1.setText("Obraz");

        jLabel2.setText("Parametry");

        jTextField1.setColumns(4);

        jTextField2.setColumns(4);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setColumns(4);

        jTextField4.setColumns(4);

        jRadioButton6.setText("modyfikacja widma");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        param1.setText("jLabel3");

        param2.setText("jLabel4");

        param3.setText("jLabel5");

        param4.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(param2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(param3)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jLabel1)
                                    .addComponent(jCheckBox1)
                                    .addComponent(param4))))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jCheckBox2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param1)
                    .addComponent(param2)
                    .addComponent(param3)
                    .addComponent(param4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    
        
        //SET PARAMS FOR GENERIC FILTER :P
        float[] params = new float[paramTab.length];
        for(int i =0; i<paramTab.length-1; ++i) {
            if (! paramTab[i].getText().isEmpty())
                params[i]=Float.parseFloat(paramTab[i].getText());
            else 
                params[i]=0;
        }
        filter.setParams(params);
        
        ///SET FILTER TYPE
        int i=0;
        for( ; i<rbTab.length; ++i)
            if ( rbTab[i].isSelected()) {
                filter.setFilter(i);
                break;
            }
        
        
        //SET POINTS FOR ENDGE DETECT FILTER
        if(i == 4) {
            Point2D p1,p2;
            
            //parse jTextField5 -> P1
            
            String[] pp = jTextField4.getText().split(",");
            if (pp.length == 2) {
                System.out.println(pp[0] + " " + pp[1]);
                p1 = new Point2D.Float(Integer.parseInt(pp[0]), Integer.parseInt(pp[1]));
                p2 = new Point2D.Float(-1*Integer.parseInt(pp[0]),-1*Integer.parseInt(pp[1]));
                filter.setP1(p1);
                filter.setP2(p2);
            }
        }
        
        //SET FREQUENCY & PHASE IMAGE DISPLAY
        filter.setAdditionalImage(0, jCheckBox1.isSelected());
        filter.setAdditionalImage(1, jCheckBox2.isSelected());
        
        
        filter.refresh();
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel param1;
    private javax.swing.JLabel param2;
    private javax.swing.JLabel param3;
    private javax.swing.JLabel param4;
    // End of variables declaration//GEN-END:variables
}
