/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package filters;

import sys.TabData;

/**
 *
 * @author pawel
 */
public class RaleighFilterPanel extends javax.swing.JPanel {

    RaleighFilter filter;

    /**
     * Creates new form RaleighFilterPanel
     */
    public RaleighFilterPanel() {
        initComponents();
    }

    RaleighFilterPanel(RaleighFilter aThis, TabData data) {
        this();
        this.filter = aThis;
        if (data.getFilteredImage().getRaster().getNumBands() == 3) {
            this.chanelPanel.setVisible(true);
            checkRed.setSelected(this.filter.getChannel()[0]);
            checkGreen.setSelected(this.filter.getChannel()[1]);
            checkBlue.setSelected(this.filter.getChannel()[2]);
        } else {
            this.chanelPanel.setVisible(false);
        }
        this.editGmin.setText(String.valueOf(this.filter.getGmin()));
        this.editAlpha.setText(String.valueOf(this.filter.getAlpha()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editGmin = new javax.swing.JTextField();
        editAlpha = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chanelPanel = new javax.swing.JPanel();
        checkLumnia = new javax.swing.JCheckBox();
        checkRed = new javax.swing.JCheckBox();
        checkGreen = new javax.swing.JCheckBox();
        checkBlue = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 100));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 80));

        editGmin.setColumns(3);
        editGmin.setText("0");

        editAlpha.setColumns(3);
        editAlpha.setText("0");
        editAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAlphaActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Minimal value:");

        jLabel2.setText("Alpha:");

        chanelPanel.setPreferredSize(new java.awt.Dimension(200, 100));

        checkLumnia.setText("By luminance");
        checkLumnia.setActionCommand("Lumnia");

        checkRed.setText("Red");

        checkGreen.setText("Green");

        checkBlue.setText("Blue");

        jLabel3.setText("Channels:");

        javax.swing.GroupLayout chanelPanelLayout = new javax.swing.GroupLayout(chanelPanel);
        chanelPanel.setLayout(chanelPanelLayout);
        chanelPanelLayout.setHorizontalGroup(
            chanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chanelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkLumnia)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(chanelPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chanelPanelLayout.setVerticalGroup(
            chanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chanelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRed)
                    .addComponent(checkGreen)
                    .addComponent(checkBlue)
                    .addComponent(checkLumnia)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editGmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chanelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editGmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(editAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applyButton)
                    .addComponent(chanelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        filter.setChannel(0, checkRed.isSelected());
        filter.setChannel(1, checkGreen.isSelected());
        filter.setChannel(2, checkBlue.isSelected());
        filter.setChannel(3, checkLumnia.isSelected());

        filter.setGmin(Integer.parseInt(editGmin.getText()));
        float alpha = 0.0f;
        try {
            alpha = Float.parseFloat(editAlpha.getText());
            filter.setAlpha(alpha);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        filter.setAlpha(alpha);
        filter.refresh();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void editAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAlphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAlphaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel chanelPanel;
    private javax.swing.JCheckBox checkBlue;
    private javax.swing.JCheckBox checkGreen;
    private javax.swing.JCheckBox checkLumnia;
    private javax.swing.JCheckBox checkRed;
    private javax.swing.JTextField editAlpha;
    private javax.swing.JTextField editGmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
