/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author Lukasz
 */
public class MiniaturImagePanel extends javax.swing.JPanel {
    private BufferedImage image;
private String imageName;
    /**
     * Creates new form MiniaturImagePanel
     */
    public MiniaturImagePanel() {
        initComponents();
    }
    
    public void setImageName(String image){
        
        imageName = image.split("\\.")[0];
        this.repaint();
    }
    
    public void setImage(BufferedImage image){
        this.image = image;
        this.repaint();
    }
    
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Paints the background
        if (image != null) {
            g.drawImage(image, 0,0, image.getWidth(), image.getHeight(), null);
        }
        else if(imageName!=null){
            g.drawString(imageName, 0, 30);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
