/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.DecimalFormat;
import sys.DTWMatch;

/**
 *
 * @author Lukasz
 */
public class MatchPreview extends javax.swing.JPanel {

    DTWMatch match;
    DecimalFormat df = new DecimalFormat("#.##");
    /**
     * Creates new form MatchPreview
     */
    public MatchPreview(DTWMatch match) {
        initComponents();
        this.match = match;
        this.wordLabel.setText(match.getWord().word);
        this.distnaceLabel.setText("nieznana");
    }

    public void Update() {
        this.wordLabel.setText(match.getWord().word);
        this.distnaceLabel.setText(df.format(match.getWarpingDistance()));
        this.miniaturImagePanel1.setImage(DTWMatch.resize(match.getImage(),100,60));
        this.localLimitsLabel.setText(match.isGlobalConstraints()?"tak":"nie");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wordLabel = new javax.swing.JLabel();
        distnaceLabel = new javax.swing.JLabel();
        miniaturImagePanel1 = new gui.ImagePanel();
        localLimitsLabel = new javax.swing.JLabel();

        wordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wordLabel.setText("wordLabel");

        distnaceLabel.setText("distnaceLabel");

        miniaturImagePanel1.setPreferredSize(new java.awt.Dimension(100, 60));
        miniaturImagePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniaturImagePanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout miniaturImagePanel1Layout = new javax.swing.GroupLayout(miniaturImagePanel1);
        miniaturImagePanel1.setLayout(miniaturImagePanel1Layout);
        miniaturImagePanel1Layout.setHorizontalGroup(
            miniaturImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        miniaturImagePanel1Layout.setVerticalGroup(
            miniaturImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        localLimitsLabel.setText("localLimitsLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(miniaturImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(distnaceLabel)
                        .addGap(51, 51, 51)
                        .addComponent(localLimitsLabel)))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distnaceLabel)
                    .addComponent(localLimitsLabel))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(miniaturImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void miniaturImagePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniaturImagePanel1MouseClicked
      DistanceImagePreviewWindow window =  new DistanceImagePreviewWindow(match.getImage());
      window.setVisible(true);
    }//GEN-LAST:event_miniaturImagePanel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distnaceLabel;
    private javax.swing.JLabel localLimitsLabel;
    private gui.ImagePanel miniaturImagePanel1;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
